version: "3.5"
services:
  dev:
    container_name: lambda-go
    build:
      context: .
      dockerfile: ./dev.dockerfile
    volumes:
      - ./app:/app
      - ./entry.sh:/entry.sh
      - ./testrun.sh:/testrun.sh
    working_dir: /app
    ports:
        - ${DEV_PORT-9000}:8080
    entrypoint: /bin/sh
    tty: true
